apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: creditcard-service
  name: creditcard-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creditcard-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: creditcard-service
    spec:
      containers:
      - image: xocbayar/creditcard-service
        name: creditcard-service
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: creditcard-service
  name: creditcard-service
spec:
  ports:
  - name: 9001-9001
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: creditcard-service
  type: ClusterIP
status:
  loadBalancer: {}
