apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: logging-service
  name: logging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: logging-service
    spec:
      containers:
      - image: xocbayar/logging-service
        name: logging-service
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: logging-service
  name: logging-service
spec:
  ports:
  - name: 9500-9500
    port: 9500
    protocol: TCP
    targetPort: 9500
  selector:
    app: logging-service
  type: ClusterIP
status:
  loadBalancer: {}
