apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sample-project
  name: sample-project
spec:
  containers:
    - image: xocbayar/sample-project:latest
      name: sample-project
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent
      env:      
        - name: SPRING_PROFILE
          value: dev
        - name: SPRING_APPLICATION_JSON
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: dev-config.json
  restartPolicy: Never  