apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  dev-config.json:
    '{
      "sample.datasource.url": "jdbc:mysql://dev-endpoint/sample",
      "sample.datasource.username": "dev-root",
      "sample.datasource.password": "dev-pass"
     }'